<a href="https://colab.research.google.com/github/nvr98/Machine_Learning_Study/blob/main/Decision_Tree_and_Random_Forest_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt


In [2]:
dataset = pd.DataFrame(pd.read_csv('Social_Network_Ads.csv'))

x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values
len(x),len(y)

(400, 400)

In [5]:
from sklearn.model_selection import train_test_split

X_train ,X_test ,Y_train ,Y_test = train_test_split(x,y,test_size = 0.2 , random_state = 42)
len(X_train),len(X_test),len(Y_train),len(Y_test)


(320, 80, 320, 80)

In [16]:
Y_test

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1])

In [6]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [21]:
from sklearn.tree import DecisionTreeClassifier

classifier = DecisionTreeClassifier(random_state = 49 , criterion='entropy')
classifier.fit(X_train,Y_train)

DecisionTreeClassifier(criterion='entropy', random_state=49)

In [22]:
Y_pred = classifier.predict(X_test)

In [25]:
from sklearn.metrics import confusion_matrix as cm , accuracy_score as acc

print(cm(Y_pred, Y_test))
acc(Y_test,Y_pred)

[[43  6]
 [ 9 22]]


0.8125

**Random Forest Classification **

In [33]:
from sklearn.ensemble import RandomForestClassifier

classifier_1 = RandomForestClassifier( n_estimators=100 , criterion='entropy',random_state = 42)
classifier_1.fit(X_train,Y_train)

RandomForestClassifier(criterion='entropy', random_state=42)

In [34]:
Y_pred = classifier_1.predict(X_test)

In [35]:
from sklearn.metrics import confusion_matrix  as cm_1 , accuracy_score as acc_1

print(cm_1(Y_pred,Y_test))
acc_1(Y_pred,Y_test)

[[45  3]
 [ 7 25]]


0.875